// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_header.proto

package org.menina.rail.protocol;

public final class RpcHeader {
  private RpcHeader() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code protocol.SerializationType}
   */
  public enum SerializationType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PROTOBUF = 0;</code>
     */
    PROTOBUF(0),
    /**
     * <code>NONE = 1;</code>
     */
    NONE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PROTOBUF = 0;</code>
     */
    public static final int PROTOBUF_VALUE = 0;
    /**
     * <code>NONE = 1;</code>
     */
    public static final int NONE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static SerializationType valueOf(int value) {
      return forNumber(value);
    }

    public static SerializationType forNumber(int value) {
      switch (value) {
        case 0: return PROTOBUF;
        case 1: return NONE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SerializationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SerializationType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SerializationType>() {
            public SerializationType findValueByNumber(int number) {
              return SerializationType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return RpcHeader.getDescriptor().getEnumTypes().get(0);
    }

    private static final SerializationType[] VALUES = values();

    public static SerializationType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SerializationType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protocol.SerializationType)
  }

  /**
   * Protobuf enum {@code protocol.CompressType}
   */
  public enum CompressType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>COMPRESS_NONE = 0;</code>
     */
    COMPRESS_NONE(0),
    /**
     * <code>SNAPPY = 1;</code>
     */
    SNAPPY(1),
    /**
     * <code>GZIP = 2;</code>
     */
    GZIP(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>COMPRESS_NONE = 0;</code>
     */
    public static final int COMPRESS_NONE_VALUE = 0;
    /**
     * <code>SNAPPY = 1;</code>
     */
    public static final int SNAPPY_VALUE = 1;
    /**
     * <code>GZIP = 2;</code>
     */
    public static final int GZIP_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static CompressType valueOf(int value) {
      return forNumber(value);
    }

    public static CompressType forNumber(int value) {
      switch (value) {
        case 0: return COMPRESS_NONE;
        case 1: return SNAPPY;
        case 2: return GZIP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CompressType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CompressType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CompressType>() {
            public CompressType findValueByNumber(int number) {
              return CompressType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return RpcHeader.getDescriptor().getEnumTypes().get(1);
    }

    private static final CompressType[] VALUES = values();

    public static CompressType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CompressType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protocol.CompressType)
  }

  /**
   * Protobuf enum {@code protocol.ResponseCode}
   */
  public enum ResponseCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <code>FAIL = 1;</code>
     */
    FAIL(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <code>FAIL = 1;</code>
     */
    public static final int FAIL_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static ResponseCode valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseCode forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return FAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResponseCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseCode>() {
            public ResponseCode findValueByNumber(int number) {
              return ResponseCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return RpcHeader.getDescriptor().getEnumTypes().get(2);
    }

    private static final ResponseCode[] VALUES = values();

    public static ResponseCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResponseCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protocol.ResponseCode)
  }

  /**
   * Protobuf enum {@code protocol.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REQUEST = 0;</code>
     */
    REQUEST(0),
    /**
     * <code>RESPONSE = 1;</code>
     */
    RESPONSE(1),
    /**
     * <code>HEARTBEAT = 2;</code>
     */
    HEARTBEAT(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>REQUEST = 0;</code>
     */
    public static final int REQUEST_VALUE = 0;
    /**
     * <code>RESPONSE = 1;</code>
     */
    public static final int RESPONSE_VALUE = 1;
    /**
     * <code>HEARTBEAT = 2;</code>
     */
    public static final int HEARTBEAT_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return REQUEST;
        case 1: return RESPONSE;
        case 2: return HEARTBEAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return RpcHeader.getDescriptor().getEnumTypes().get(3);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protocol.MessageType)
  }

  public interface RequestHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.RequestHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 requestId = 1;</code>
     */
    long getRequestId();

    /**
     * <code>uint32 bodyLength = 2;</code>
     */
    int getBodyLength();

    /**
     * <code>string method_name = 3;</code>
     */
    String getMethodName();
    /**
     * <code>string method_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>string version = 4;</code>
     */
    String getVersion();
    /**
     * <code>string version = 4;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>.protocol.CompressType compress_type = 5;</code>
     */
    int getCompressTypeValue();
    /**
     * <code>.protocol.CompressType compress_type = 5;</code>
     */
    CompressType getCompressType();

    /**
     * <code>.protocol.MessageType message_type = 6;</code>
     */
    int getMessageTypeValue();
    /**
     * <code>.protocol.MessageType message_type = 6;</code>
     */
    MessageType getMessageType();

    /**
     * <code>map&lt;string, string&gt; attachments = 7;</code>
     */
    int getAttachmentsCount();
    /**
     * <code>map&lt;string, string&gt; attachments = 7;</code>
     */
    boolean containsAttachments(
            String key);
    /**
     * Use {@link #getAttachmentsMap()} instead.
     */
    @Deprecated
    java.util.Map<String, String>
    getAttachments();
    /**
     * <code>map&lt;string, string&gt; attachments = 7;</code>
     */
    java.util.Map<String, String>
    getAttachmentsMap();
    /**
     * <code>map&lt;string, string&gt; attachments = 7;</code>
     */

    String getAttachmentsOrDefault(
            String key,
            String defaultValue);
    /**
     * <code>map&lt;string, string&gt; attachments = 7;</code>
     */

    String getAttachmentsOrThrow(
            String key);
  }
  /**
   * Protobuf type {@code protocol.RequestHeader}
   */
  public  static final class RequestHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.RequestHeader)
      RequestHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestHeader.newBuilder() to construct.
    private RequestHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestHeader() {
      requestId_ = 0L;
      bodyLength_ = 0;
      methodName_ = "";
      version_ = "";
      compressType_ = 0;
      messageType_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              requestId_ = input.readUInt64();
              break;
            }
            case 16: {

              bodyLength_ = input.readUInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              methodName_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              compressType_ = rawValue;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              messageType_ = rawValue;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                attachments_ = com.google.protobuf.MapField.newMapField(
                    AttachmentsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000040;
              }
              com.google.protobuf.MapEntry<String, String>
              attachments__ = input.readMessage(
                  AttachmentsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              attachments_.getMutableMap().put(
                  attachments__.getKey(), attachments__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcHeader.internal_static_protocol_RequestHeader_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetAttachments();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcHeader.internal_static_protocol_RequestHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestHeader.class, Builder.class);
    }

    private int bitField0_;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private long requestId_;
    /**
     * <code>uint64 requestId = 1;</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int BODYLENGTH_FIELD_NUMBER = 2;
    private int bodyLength_;
    /**
     * <code>uint32 bodyLength = 2;</code>
     */
    public int getBodyLength() {
      return bodyLength_;
    }

    public static final int METHOD_NAME_FIELD_NUMBER = 3;
    private volatile Object methodName_;
    /**
     * <code>string method_name = 3;</code>
     */
    public String getMethodName() {
      Object ref = methodName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>string method_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 4;
    private volatile Object version_;
    /**
     * <code>string version = 4;</code>
     */
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 4;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPRESS_TYPE_FIELD_NUMBER = 5;
    private int compressType_;
    /**
     * <code>.protocol.CompressType compress_type = 5;</code>
     */
    public int getCompressTypeValue() {
      return compressType_;
    }
    /**
     * <code>.protocol.CompressType compress_type = 5;</code>
     */
    public CompressType getCompressType() {
      @SuppressWarnings("deprecation")
      CompressType result = CompressType.valueOf(compressType_);
      return result == null ? CompressType.UNRECOGNIZED : result;
    }

    public static final int MESSAGE_TYPE_FIELD_NUMBER = 6;
    private int messageType_;
    /**
     * <code>.protocol.MessageType message_type = 6;</code>
     */
    public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.protocol.MessageType message_type = 6;</code>
     */
    public MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      MessageType result = MessageType.valueOf(messageType_);
      return result == null ? MessageType.UNRECOGNIZED : result;
    }

    public static final int ATTACHMENTS_FIELD_NUMBER = 7;
    private static final class AttachmentsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, String>newDefaultInstance(
                  RpcHeader.internal_static_protocol_RequestHeader_AttachmentsEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        String, String> attachments_;
    private com.google.protobuf.MapField<String, String>
    internalGetAttachments() {
      if (attachments_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttachmentsDefaultEntryHolder.defaultEntry);
      }
      return attachments_;
    }

    public int getAttachmentsCount() {
      return internalGetAttachments().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; attachments = 7;</code>
     */

    public boolean containsAttachments(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetAttachments().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttachmentsMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, String> getAttachments() {
      return getAttachmentsMap();
    }
    /**
     * <code>map&lt;string, string&gt; attachments = 7;</code>
     */

    public java.util.Map<String, String> getAttachmentsMap() {
      return internalGetAttachments().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; attachments = 7;</code>
     */

    public String getAttachmentsOrDefault(
        String key,
        String defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetAttachments().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; attachments = 7;</code>
     */

    public String getAttachmentsOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, String> map =
          internalGetAttachments().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestId_ != 0L) {
        output.writeUInt64(1, requestId_);
      }
      if (bodyLength_ != 0) {
        output.writeUInt32(2, bodyLength_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, methodName_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, version_);
      }
      if (compressType_ != CompressType.COMPRESS_NONE.getNumber()) {
        output.writeEnum(5, compressType_);
      }
      if (messageType_ != MessageType.REQUEST.getNumber()) {
        output.writeEnum(6, messageType_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAttachments(),
          AttachmentsDefaultEntryHolder.defaultEntry,
          7);
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, requestId_);
      }
      if (bodyLength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, bodyLength_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, methodName_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, version_);
      }
      if (compressType_ != CompressType.COMPRESS_NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, compressType_);
      }
      if (messageType_ != MessageType.REQUEST.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, messageType_);
      }
      for (java.util.Map.Entry<String, String> entry
           : internalGetAttachments().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, String>
        attachments__ = AttachmentsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, attachments__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RequestHeader)) {
        return super.equals(obj);
      }
      RequestHeader other = (RequestHeader) obj;

      boolean result = true;
      result = result && (getRequestId()
          == other.getRequestId());
      result = result && (getBodyLength()
          == other.getBodyLength());
      result = result && getMethodName()
          .equals(other.getMethodName());
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && compressType_ == other.compressType_;
      result = result && messageType_ == other.messageType_;
      result = result && internalGetAttachments().equals(
          other.internalGetAttachments());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (37 * hash) + BODYLENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getBodyLength();
      hash = (37 * hash) + METHOD_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + COMPRESS_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + compressType_;
      hash = (37 * hash) + MESSAGE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + messageType_;
      if (!internalGetAttachments().getMap().isEmpty()) {
        hash = (37 * hash) + ATTACHMENTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAttachments().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RequestHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RequestHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RequestHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.RequestHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.RequestHeader)
        RequestHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcHeader.internal_static_protocol_RequestHeader_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetAttachments();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetMutableAttachments();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcHeader.internal_static_protocol_RequestHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestHeader.class, Builder.class);
      }

      // Construct using org.menina.rpc.protocol.RpcHeader.RequestHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        requestId_ = 0L;

        bodyLength_ = 0;

        methodName_ = "";

        version_ = "";

        compressType_ = 0;

        messageType_ = 0;

        internalGetMutableAttachments().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcHeader.internal_static_protocol_RequestHeader_descriptor;
      }

      @Override
      public RequestHeader getDefaultInstanceForType() {
        return RequestHeader.getDefaultInstance();
      }

      @Override
      public RequestHeader build() {
        RequestHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RequestHeader buildPartial() {
        RequestHeader result = new RequestHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.requestId_ = requestId_;
        result.bodyLength_ = bodyLength_;
        result.methodName_ = methodName_;
        result.version_ = version_;
        result.compressType_ = compressType_;
        result.messageType_ = messageType_;
        result.attachments_ = internalGetAttachments();
        result.attachments_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestHeader) {
          return mergeFrom((RequestHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestHeader other) {
        if (other == RequestHeader.getDefaultInstance()) return this;
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        if (other.getBodyLength() != 0) {
          setBodyLength(other.getBodyLength());
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.compressType_ != 0) {
          setCompressTypeValue(other.getCompressTypeValue());
        }
        if (other.messageType_ != 0) {
          setMessageTypeValue(other.getMessageTypeValue());
        }
        internalGetMutableAttachments().mergeFrom(
            other.internalGetAttachments());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long requestId_ ;
      /**
       * <code>uint64 requestId = 1;</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>uint64 requestId = 1;</code>
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private int bodyLength_ ;
      /**
       * <code>uint32 bodyLength = 2;</code>
       */
      public int getBodyLength() {
        return bodyLength_;
      }
      /**
       * <code>uint32 bodyLength = 2;</code>
       */
      public Builder setBodyLength(int value) {
        
        bodyLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 bodyLength = 2;</code>
       */
      public Builder clearBodyLength() {
        
        bodyLength_ = 0;
        onChanged();
        return this;
      }

      private Object methodName_ = "";
      /**
       * <code>string method_name = 3;</code>
       */
      public String getMethodName() {
        Object ref = methodName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string method_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method_name = 3;</code>
       */
      public Builder setMethodName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method_name = 3;</code>
       */
      public Builder clearMethodName() {
        
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>string method_name = 3;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        methodName_ = value;
        onChanged();
        return this;
      }

      private Object version_ = "";
      /**
       * <code>string version = 4;</code>
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string version = 4;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 4;</code>
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 4;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 4;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private int compressType_ = 0;
      /**
       * <code>.protocol.CompressType compress_type = 5;</code>
       */
      public int getCompressTypeValue() {
        return compressType_;
      }
      /**
       * <code>.protocol.CompressType compress_type = 5;</code>
       */
      public Builder setCompressTypeValue(int value) {
        compressType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.CompressType compress_type = 5;</code>
       */
      public CompressType getCompressType() {
        @SuppressWarnings("deprecation")
        CompressType result = CompressType.valueOf(compressType_);
        return result == null ? CompressType.UNRECOGNIZED : result;
      }
      /**
       * <code>.protocol.CompressType compress_type = 5;</code>
       */
      public Builder setCompressType(CompressType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        compressType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.CompressType compress_type = 5;</code>
       */
      public Builder clearCompressType() {
        
        compressType_ = 0;
        onChanged();
        return this;
      }

      private int messageType_ = 0;
      /**
       * <code>.protocol.MessageType message_type = 6;</code>
       */
      public int getMessageTypeValue() {
        return messageType_;
      }
      /**
       * <code>.protocol.MessageType message_type = 6;</code>
       */
      public Builder setMessageTypeValue(int value) {
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.MessageType message_type = 6;</code>
       */
      public MessageType getMessageType() {
        @SuppressWarnings("deprecation")
        MessageType result = MessageType.valueOf(messageType_);
        return result == null ? MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.protocol.MessageType message_type = 6;</code>
       */
      public Builder setMessageType(MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.MessageType message_type = 6;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          String, String> attachments_;
      private com.google.protobuf.MapField<String, String>
      internalGetAttachments() {
        if (attachments_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AttachmentsDefaultEntryHolder.defaultEntry);
        }
        return attachments_;
      }
      private com.google.protobuf.MapField<String, String>
      internalGetMutableAttachments() {
        onChanged();;
        if (attachments_ == null) {
          attachments_ = com.google.protobuf.MapField.newMapField(
              AttachmentsDefaultEntryHolder.defaultEntry);
        }
        if (!attachments_.isMutable()) {
          attachments_ = attachments_.copy();
        }
        return attachments_;
      }

      public int getAttachmentsCount() {
        return internalGetAttachments().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; attachments = 7;</code>
       */

      public boolean containsAttachments(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetAttachments().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAttachmentsMap()} instead.
       */
      @Deprecated
      public java.util.Map<String, String> getAttachments() {
        return getAttachmentsMap();
      }
      /**
       * <code>map&lt;string, string&gt; attachments = 7;</code>
       */

      public java.util.Map<String, String> getAttachmentsMap() {
        return internalGetAttachments().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; attachments = 7;</code>
       */

      public String getAttachmentsOrDefault(
          String key,
          String defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetAttachments().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; attachments = 7;</code>
       */

      public String getAttachmentsOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, String> map =
            internalGetAttachments().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAttachments() {
        internalGetMutableAttachments().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; attachments = 7;</code>
       */

      public Builder removeAttachments(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableAttachments().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, String>
      getMutableAttachments() {
        return internalGetMutableAttachments().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; attachments = 7;</code>
       */
      public Builder putAttachments(
          String key,
          String value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableAttachments().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; attachments = 7;</code>
       */

      public Builder putAllAttachments(
          java.util.Map<String, String> values) {
        internalGetMutableAttachments().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.RequestHeader)
    }

    // @@protoc_insertion_point(class_scope:protocol.RequestHeader)
    private static final RequestHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RequestHeader();
    }

    public static RequestHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestHeader>
        PARSER = new com.google.protobuf.AbstractParser<RequestHeader>() {
      @Override
      public RequestHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestHeader> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RequestHeader> getParserForType() {
      return PARSER;
    }

    @Override
    public RequestHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protocol.ResponseHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint64 requestId = 1;</code>
     */
    long getRequestId();

    /**
     * <code>uint32 bodyLength = 2;</code>
     */
    int getBodyLength();

    /**
     * <code>.protocol.ResponseCode response_code = 3;</code>
     */
    int getResponseCodeValue();
    /**
     * <code>.protocol.ResponseCode response_code = 3;</code>
     */
    ResponseCode getResponseCode();

    /**
     * <code>string response_message = 4;</code>
     */
    String getResponseMessage();
    /**
     * <code>string response_message = 4;</code>
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();
  }
  /**
   * Protobuf type {@code protocol.ResponseHeader}
   */
  public  static final class ResponseHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protocol.ResponseHeader)
      ResponseHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseHeader.newBuilder() to construct.
    private ResponseHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseHeader() {
      requestId_ = 0L;
      bodyLength_ = 0;
      responseCode_ = 0;
      responseMessage_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              requestId_ = input.readUInt64();
              break;
            }
            case 16: {

              bodyLength_ = input.readUInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              responseCode_ = rawValue;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              responseMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RpcHeader.internal_static_protocol_ResponseHeader_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RpcHeader.internal_static_protocol_ResponseHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ResponseHeader.class, Builder.class);
    }

    public static final int REQUESTID_FIELD_NUMBER = 1;
    private long requestId_;
    /**
     * <code>uint64 requestId = 1;</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int BODYLENGTH_FIELD_NUMBER = 2;
    private int bodyLength_;
    /**
     * <code>uint32 bodyLength = 2;</code>
     */
    public int getBodyLength() {
      return bodyLength_;
    }

    public static final int RESPONSE_CODE_FIELD_NUMBER = 3;
    private int responseCode_;
    /**
     * <code>.protocol.ResponseCode response_code = 3;</code>
     */
    public int getResponseCodeValue() {
      return responseCode_;
    }
    /**
     * <code>.protocol.ResponseCode response_code = 3;</code>
     */
    public ResponseCode getResponseCode() {
      @SuppressWarnings("deprecation")
      ResponseCode result = ResponseCode.valueOf(responseCode_);
      return result == null ? ResponseCode.UNRECOGNIZED : result;
    }

    public static final int RESPONSE_MESSAGE_FIELD_NUMBER = 4;
    private volatile Object responseMessage_;
    /**
     * <code>string response_message = 4;</code>
     */
    public String getResponseMessage() {
      Object ref = responseMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string response_message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      Object ref = responseMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestId_ != 0L) {
        output.writeUInt64(1, requestId_);
      }
      if (bodyLength_ != 0) {
        output.writeUInt32(2, bodyLength_);
      }
      if (responseCode_ != ResponseCode.SUCCESS.getNumber()) {
        output.writeEnum(3, responseCode_);
      }
      if (!getResponseMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, responseMessage_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, requestId_);
      }
      if (bodyLength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, bodyLength_);
      }
      if (responseCode_ != ResponseCode.SUCCESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, responseCode_);
      }
      if (!getResponseMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, responseMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ResponseHeader)) {
        return super.equals(obj);
      }
      ResponseHeader other = (ResponseHeader) obj;

      boolean result = true;
      result = result && (getRequestId()
          == other.getRequestId());
      result = result && (getBodyLength()
          == other.getBodyLength());
      result = result && responseCode_ == other.responseCode_;
      result = result && getResponseMessage()
          .equals(other.getResponseMessage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (37 * hash) + BODYLENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getBodyLength();
      hash = (37 * hash) + RESPONSE_CODE_FIELD_NUMBER;
      hash = (53 * hash) + responseCode_;
      hash = (37 * hash) + RESPONSE_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ResponseHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ResponseHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ResponseHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResponseHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResponseHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ResponseHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ResponseHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ResponseHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ResponseHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protocol.ResponseHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protocol.ResponseHeader)
        ResponseHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RpcHeader.internal_static_protocol_ResponseHeader_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RpcHeader.internal_static_protocol_ResponseHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ResponseHeader.class, Builder.class);
      }

      // Construct using org.menina.rpc.protocol.RpcHeader.ResponseHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        requestId_ = 0L;

        bodyLength_ = 0;

        responseCode_ = 0;

        responseMessage_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RpcHeader.internal_static_protocol_ResponseHeader_descriptor;
      }

      @Override
      public ResponseHeader getDefaultInstanceForType() {
        return ResponseHeader.getDefaultInstance();
      }

      @Override
      public ResponseHeader build() {
        ResponseHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ResponseHeader buildPartial() {
        ResponseHeader result = new ResponseHeader(this);
        result.requestId_ = requestId_;
        result.bodyLength_ = bodyLength_;
        result.responseCode_ = responseCode_;
        result.responseMessage_ = responseMessage_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ResponseHeader) {
          return mergeFrom((ResponseHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ResponseHeader other) {
        if (other == ResponseHeader.getDefaultInstance()) return this;
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        if (other.getBodyLength() != 0) {
          setBodyLength(other.getBodyLength());
        }
        if (other.responseCode_ != 0) {
          setResponseCodeValue(other.getResponseCodeValue());
        }
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ResponseHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ResponseHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long requestId_ ;
      /**
       * <code>uint64 requestId = 1;</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>uint64 requestId = 1;</code>
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 requestId = 1;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private int bodyLength_ ;
      /**
       * <code>uint32 bodyLength = 2;</code>
       */
      public int getBodyLength() {
        return bodyLength_;
      }
      /**
       * <code>uint32 bodyLength = 2;</code>
       */
      public Builder setBodyLength(int value) {
        
        bodyLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 bodyLength = 2;</code>
       */
      public Builder clearBodyLength() {
        
        bodyLength_ = 0;
        onChanged();
        return this;
      }

      private int responseCode_ = 0;
      /**
       * <code>.protocol.ResponseCode response_code = 3;</code>
       */
      public int getResponseCodeValue() {
        return responseCode_;
      }
      /**
       * <code>.protocol.ResponseCode response_code = 3;</code>
       */
      public Builder setResponseCodeValue(int value) {
        responseCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.ResponseCode response_code = 3;</code>
       */
      public ResponseCode getResponseCode() {
        @SuppressWarnings("deprecation")
        ResponseCode result = ResponseCode.valueOf(responseCode_);
        return result == null ? ResponseCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.protocol.ResponseCode response_code = 3;</code>
       */
      public Builder setResponseCode(ResponseCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        responseCode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protocol.ResponseCode response_code = 3;</code>
       */
      public Builder clearResponseCode() {
        
        responseCode_ = 0;
        onChanged();
        return this;
      }

      private Object responseMessage_ = "";
      /**
       * <code>string response_message = 4;</code>
       */
      public String getResponseMessage() {
        Object ref = responseMessage_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string response_message = 4;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string response_message = 4;</code>
       */
      public Builder setResponseMessage(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string response_message = 4;</code>
       */
      public Builder clearResponseMessage() {
        
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string response_message = 4;</code>
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMessage_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protocol.ResponseHeader)
    }

    // @@protoc_insertion_point(class_scope:protocol.ResponseHeader)
    private static final ResponseHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ResponseHeader();
    }

    public static ResponseHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseHeader>
        PARSER = new com.google.protobuf.AbstractParser<ResponseHeader>() {
      @Override
      public ResponseHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseHeader> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ResponseHeader> getParserForType() {
      return PARSER;
    }

    @Override
    public ResponseHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_RequestHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_RequestHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_RequestHeader_AttachmentsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_RequestHeader_AttachmentsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ResponseHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_ResponseHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020rpc_header.proto\022\010protocol\"\253\002\n\rRequest" +
      "Header\022\021\n\trequestId\030\001 \001(\004\022\022\n\nbodyLength\030" +
      "\002 \001(\r\022\023\n\013method_name\030\003 \001(\t\022\017\n\007version\030\004 " +
      "\001(\t\022-\n\rcompress_type\030\005 \001(\0162\026.protocol.Co" +
      "mpressType\022+\n\014message_type\030\006 \001(\0162\025.proto" +
      "col.MessageType\022=\n\013attachments\030\007 \003(\0132(.p" +
      "rotocol.RequestHeader.AttachmentsEntry\0322" +
      "\n\020AttachmentsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\001\"\200\001\n\016ResponseHeader\022\021\n\trequest" +
      "Id\030\001 \001(\004\022\022\n\nbodyLength\030\002 \001(\r\022-\n\rresponse" +
      "_code\030\003 \001(\0162\026.protocol.ResponseCode\022\030\n\020r" +
      "esponse_message\030\004 \001(\t*+\n\021SerializationTy" +
      "pe\022\014\n\010PROTOBUF\020\000\022\010\n\004NONE\020\001*7\n\014CompressTy" +
      "pe\022\021\n\rCOMPRESS_NONE\020\000\022\n\n\006SNAPPY\020\001\022\010\n\004GZI" +
      "P\020\002*%\n\014ResponseCode\022\013\n\007SUCCESS\020\000\022\010\n\004FAIL" +
      "\020\001*7\n\013MessageType\022\013\n\007REQUEST\020\000\022\014\n\010RESPON" +
      "SE\020\001\022\r\n\tHEARTBEAT\020\002B$\n\027org.menina.rpc.pr" +
      "otocolB\tRpcHeaderb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_RequestHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_RequestHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_RequestHeader_descriptor,
        new String[] { "RequestId", "BodyLength", "MethodName", "Version", "CompressType", "MessageType", "Attachments", });
    internal_static_protocol_RequestHeader_AttachmentsEntry_descriptor =
      internal_static_protocol_RequestHeader_descriptor.getNestedTypes().get(0);
    internal_static_protocol_RequestHeader_AttachmentsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_RequestHeader_AttachmentsEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_protocol_ResponseHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_ResponseHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_ResponseHeader_descriptor,
        new String[] { "RequestId", "BodyLength", "ResponseCode", "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
